CREATE DATABASE tallerdb;

USE tallerdb;
-- Crear la tabla SUCURSALES sin la restricci�n de clave for�nea
CREATE TABLE SUCURSALES (
    RIFSuc VARCHAR(12) NOT NULL PRIMARY KEY,
    NombreSuc VARCHAR(50) NOT NULL,
    Ciudad VARCHAR(70) NOT NULL,
    Encargado VARCHAR(8),
    FechaInEnc DATE
);

-- Crear la tabla TRABAJADORES con la restricci�n de clave for�nea
CREATE TABLE TRABAJADORES (
    Cedula VARCHAR(8) NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Direccion VARCHAR(100) NOT NULL,
    Salario DECIMAL(10, 2) NOT NULL CHECK (Salario > 0),
    Telofono VARCHAR(12),
    RIFSuc VARCHAR(12),
    FOREIGN KEY (RIFSuc) REFERENCES SUCURSALES(RIFSuc) ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Agregar la restricci�n de clave for�nea a la tabla SUCURSALES
ALTER TABLE SUCURSALES
ADD FOREIGN KEY (Encargado) REFERENCES TRABAJADORES(Cedula) ON UPDATE NO ACTION ON DELETE NO ACTION;



-- Tabla RESPONSABLES
CREATE TABLE RESPONSABLES (
    CIResponsable VARCHAR(8) NOT NULL PRIMARY KEY,
    NombreResponsable VARCHAR(30) NOT NULL
);



-- Tabla FACTURAS_PROVEEDORES
CREATE TABLE FACTURAS_PROVEEDORES (
    NumFact INT NOT NULL PRIMARY KEY,
    Monto DECIMAL(10, 2) NOT NULL CHECK (Monto > 0),
    Fecha DATE NOT NULL
);
-- Tabla MARCAS_VEHICULOS
CREATE TABLE MARCAS_VEHICULOS (
    CodMarcaVeh INT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

-- Tabla TIPOS_VEHICULOS
CREATE TABLE TIPOS_VEHICULOS (
    CodTipoV INT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);

-- Tabla LINEAS
CREATE TABLE LINEAS (
    CodLineas INT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);

-- Tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    Rif VARCHAR(12) NOT NULL PRIMARY KEY,
    RazonSocial VARCHAR(25) NOT NULL,
    Direccion VARCHAR(50) NOT NULL,
    TelefonoL VARCHAR(10) NOT NULL,
    TelefonoC VARCHAR(11) NOT NULL,
    PersonaCont VARCHAR(25) NOT NULL
);

-- Tabla MODELOS_VEHICULOS
CREATE TABLE MODELOS_VEHICULOS (
    CodMarcaV INT NOT NULL,
    CodConsec INT NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    CantPuestos INT NOT NULL,
    Peso DECIMAL(10, 2) NOT NULL,
    TipoAceite VARCHAR(25) NOT NULL,
    AceiteCaja VARCHAR(25) NOT NULL,
    TipoRefri VARCHAR(25) NOT NULL,
    Octanaje INT NOT NULL CHECK (Octanaje IN (91, 95)),
    TipoMant VARCHAR(30) NOT NULL,
    TiempoUsoMant INT NOT NULL,
    KilometrajeMant DECIMAL(10, 2) NOT NULL,
    CodTipoV INT NOT NULL,
    PRIMARY KEY (CodMarcaV, CodConsec),
    FOREIGN KEY (CodTipoV) REFERENCES TIPOS_VEHICULOS(CodTipoV) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla VEHICULOS
CREATE TABLE VEHICULOS (
    CodVehiculo INT NOT NULL PRIMARY KEY,
    Placa VARCHAR(6) NOT NULL,
    TipoAceite VARCHAR(15) NOT NULL,
    FechaAdq DATETIME NOT NULL,
    CiResp VARCHAR(8) NOT NULL,
    CodMarca INT NOT NULL,
    NumModelo INT NOT NULL,
    FOREIGN KEY (CiResp) REFERENCES RESPONSABLES(CIResponsable) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodMarca, NumModelo) REFERENCES MODELOS_VEHICULOS(CodMarcaV, CodConsec) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla FACTURAS_SERVICIOS
CREATE TABLE FACTURAS_SERVICIOS (
    CodF INT NOT NULL PRIMARY KEY,
    Fecha DATE NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL CHECK (Monto > 0),
    Descuento DECIMAL(14) NOT NULL
);


-- Tabla AUTORIZADOS
CREATE TABLE AUTORIZADOS (
    CIAutorizado VARCHAR(8) NOT NULL PRIMARY KEY,
    NombreAutorizado VARCHAR(30) NOT NULL
);
-- Tabla ORDENES_SERVICIOS
CREATE TABLE ORDENES_SERVICIOS (
    Nro INT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    FechaHoraE DATE NOT NULL,
    FechaHoraSEstimada DATE NOT NULL,
    CIAutorizado VARCHAR(8),
    NumFacturaServ INT NOT NULL,
    CodVehiculo INT NOT NULL,
    CIEmpleado VARCHAR(8) NOT NULL,
    FOREIGN KEY (CIAutorizado) REFERENCES AUTORIZADOS(CIAutorizado) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (NumFacturaServ) REFERENCES FACTURAS_SERVICIOS(CodF) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodVehiculo) REFERENCES VEHICULOS(CodVehiculo) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CIEmpleado) REFERENCES TRABAJADORES(Cedula) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla SERVICIOS
CREATE TABLE SERVICIOS (
    CodigoServ INT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NOT NULL,
    CI_Coord VARCHAR(8) NOT NULL,
    FOREIGN KEY (CI_Coord) REFERENCES TRABAJADORES(Cedula) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    CodProd INT NOT NULL PRIMARY KEY,
    NombreP VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL CHECK (Precio > 0),
    Ecologico CHAR(1) NOT NULL CHECK (Ecologico IN ('S', 'N')),
    Existencia INT NOT NULL CHECK (Existencia >= 0),
    Fabricante VARCHAR(50) NOT NULL,
    Maximo INT NOT NULL CHECK (Maximo > 0),
    Minimo INT NOT NULL CHECK (Minimo > 0),
	CHECK (Minimo<=Maximo),
    TipoPro VARCHAR(10) NOT NULL CHECK (TipoPro IN ('Servicio', 'Tienda')),
    CodLinea INT NOT NULL,
    FOREIGN KEY (CodLinea) REFERENCES LINEAS(CodLineas) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla PRODUCTOS_SERVICIOS
CREATE TABLE PRODUCTOS_SERVICIOS (
    CodProd INT NOT NULL PRIMARY KEY,
    FOREIGN KEY (CodProd) REFERENCES PRODUCTOS(CodProd) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla PRODUCTOS_TIENDA
CREATE TABLE PRODUCTOS_TIENDA (
    CodProd INT NOT NULL PRIMARY KEY,
    FOREIGN KEY (CodProd) REFERENCES PRODUCTOS(CodProd) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla REQUISICIONES_COMPRA
CREATE TABLE REQUISICIONES_COMPRA (
    IdReq INT NOT NULL PRIMARY KEY,
    Fecha DATE NOT NULL,
    CantProd INT NOT NULL CHECK (CantProd > 0),
    CodProd INT NOT NULL,
    FOREIGN KEY (CodProd) REFERENCES PRODUCTOS(CodProd) ON UPDATE CASCADE ON DELETE NO ACTION
);



-- Tabla PAGOS
CREATE TABLE PAGOS (
    CodPago INT NOT NULL PRIMARY KEY,
    Fecha DATE NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL CHECK (Monto > 0),
    TipoPago CHAR(1) NOT NULL CHECK (TipoPago IN ('E', 'P', 'T')), -- E: Efectivo, P: Pago Movil, T: Tarjeta
    TipoEfectivo CHAR(1) CHECK (TipoEfectivo IN ('D', 'B')), -- D: Divisa, B: Bolivares
    Referencia INT,
    NroTelf VARCHAR(11),
    TipoTarjeta VARCHAR(7) CHECK (TipoTarjeta IN ('Debito', 'Credito')),
    Banco VARCHAR(20),
    NumTarjeta VARCHAR(20) CHECK (LEN(NumTarjeta) > 15),
    NumFacturaServicio INT,
    NumR INT,
    FOREIGN KEY (NumFacturaServicio) REFERENCES FACTURAS_SERVICIOS(CodF) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla RESERVAS
CREATE TABLE RESERVAS (
    NroR INT NOT NULL PRIMARY KEY,
    FechaR DATE NOT NULL,
    Abono DECIMAL(10, 2) NOT NULL CHECK (Abono > 0),
    CodVehiculo INT NOT NULL,
    FOREIGN KEY (CodVehiculo) REFERENCES VEHICULOS(CodVehiculo) ON UPDATE CASCADE ON DELETE NO ACTION
);




-- Tabla ORDENES_COMPRAS
CREATE TABLE ORDENES_COMPRAS (
    CodOrden INT NOT NULL PRIMARY KEY,
    NumFactProv INT NOT NULL,
    RIFProv VARCHAR(12) NOT NULL,
    CodRequiCom INT NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL CHECK (Precio > 0),
    CantidadProd INT NOT NULL CHECK (CantidadProd > 0),
    RIFSuc VARCHAR(12) NOT NULL,
    FOREIGN KEY (NumFactProv) REFERENCES FACTURAS_PROVEEDORES(NumFact) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (RIFProv) REFERENCES PROVEEDORES(Rif) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodRequiCom) REFERENCES REQUISICIONES_COMPRA(IdReq) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (RIFSuc) REFERENCES SUCURSALES(RIFSuc) ON UPDATE CASCADE ON DELETE NO ACTION
);






-- Tabla FACTURAS_TIENDAS
CREATE TABLE FACTURAS_TIENDAS (
    CodF INT NOT NULL PRIMARY KEY,
    Fecha DATE NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL CHECK (Monto > 0),
    Descuento DECIMAL(14) NOT NULL,
    CodPago INT NOT NULL,
    FOREIGN KEY (CodPago) REFERENCES PAGOS(CodPago) ON UPDATE CASCADE ON DELETE NO ACTION
);


-- Tabla DESCUENTOS
CREATE TABLE DESCUENTOS (
    RIFSuc VARCHAR(12) NOT NULL,
    NroDesc INT NOT NULL,
    LimiteInfe INT NOT NULL CHECK (LimiteInfe > 0),
    LimiteSup INT NOT NULL,
    PorcentajeDesc DECIMAL(14) NOT NULL,
	CHECK (LimiteSup >= LimiteInfe),
    PRIMARY KEY (RIFSuc, NroDesc),
    FOREIGN KEY (RIFSuc) REFERENCES SUCURSALES(RIFSuc) ON UPDATE CASCADE ON DELETE NO ACTION
);


-- Tabla INVENTARIOS
CREATE TABLE INVENTARIOS (
    RIFSuc VARCHAR(12) NOT NULL,
    NumInventario INT NOT NULL,
    FechaRealiz DATE NOT NULL,
    CodProducto INT NOT NULL,
    FechaHoraAjust DATETIME NOT NULL,
    TipoAjuste VARCHAR(25) NOT NULL,
    ExistAjustada INT NOT NULL,
    ExistReal INT NOT NULL,
    ExistTeorica DECIMAL(14) NOT NULL,
    PRIMARY KEY (RIFSuc, NumInventario),
    FOREIGN KEY (RIFSuc) REFERENCES SUCURSALES(RIFSuc) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodProducto) REFERENCES PRODUCTOS(CodProd) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla ACTIVIDADES
CREATE TABLE ACTIVIDADES (
    CodServicio INT NOT NULL,
    NroActividad INT NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Monto DECIMAL(10, 2) NOT NULL,
    AntelacionReserva INT NOT NULL,
    PRIMARY KEY (CodServicio, NroActividad),
    FOREIGN KEY (CodServicio) REFERENCES SERVICIOS(CodigoServ) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla DISTRIBUYEN
CREATE TABLE DISTRIBUYEN (
    RIFProveedor VARCHAR(12) NOT NULL,
    CodLinea INT NOT NULL,
    PRIMARY KEY (RIFProveedor, CodLinea),
    FOREIGN KEY (RIFProveedor) REFERENCES PROVEEDORES(Rif) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodLinea) REFERENCES LINEAS(CodLineas) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla REGISTRAN_FACT_PROD
CREATE TABLE REGISTRAN_FACT_PROD (
    NumFactTienda INT NOT NULL,
    CodProdTienda INT NOT NULL,
    PRIMARY KEY (NumFactTienda, CodProdTienda),
    FOREIGN KEY (NumFactTienda) REFERENCES FACTURAS_TIENDAS(CodF) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodProdTienda) REFERENCES PRODUCTOS_TIENDA(CodProd) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla RECIBEN_SUC_TIPOV
CREATE TABLE RECIBEN_SUC_TIPOV (
    RIFSucursal VARCHAR(12) NOT NULL,
    CodTipoV INT NOT NULL,
    PRIMARY KEY (RIFSucursal, CodTipoV),
    FOREIGN KEY (RIFSucursal) REFERENCES SUCURSALES(RIFSuc) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodTipoV) REFERENCES TIPOS_VEHICULOS(CodTipoV) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla APARTAN_RES_ACT
CREATE TABLE APARTAN_RES_ACT (
    NroReserva INT NOT NULL,
    CodServicio INT NOT NULL,
    NroActividad INT NOT NULL,
    FechaEjecucion DATE NOT NULL,
    PRIMARY KEY (NroReserva, CodServicio, NroActividad),
    FOREIGN KEY (NroReserva) REFERENCES RESERVAS(NroR) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (CodServicio, NroActividad) REFERENCES ACTIVIDADES(CodServicio, NroActividad) ON UPDATE CASCADE ON DELETE NO ACTION
);


-- Tabla TELEFONOS_DUENOS
CREATE TABLE TELEFONOS_DUENOS (
    CodVehiculo INT NOT NULL,
    NroTelefono VARCHAR(11) NOT NULL,
    PRIMARY KEY (CodVehiculo, NroTelefono),
    FOREIGN KEY (CodVehiculo) REFERENCES VEHICULOS(CodVehiculo) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla MANTENIMIENTO_VEHICULO
CREATE TABLE MANTENIMIENTO_VEHICULO (
    CodVehiculo INT NOT NULL,
    FechaMant DATE NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    PRIMARY KEY (CodVehiculo, FechaMant, Descripcion),
    FOREIGN KEY (CodVehiculo) REFERENCES VEHICULOS(CodVehiculo) ON UPDATE CASCADE ON DELETE NO ACTION
);

-- Tabla CONTRATAN_ACT_ORDENS_PROD_SERV
CREATE TABLE CONTRATAN_ACT_ORDENS_PROD_SERV (
    CodServicio INT NOT NULL,
    NroActividad INT NOT NULL,
    NroOrenServ INT NOT NULL,
    CodProductoServ INT NOT NULL,
    CantProd INT NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL,
    CantHoras INT NOT NULL,
    PRIMARY KEY (CodServicio, NroActividad, NroOrenServ, CodProductoServ),
    FOREIGN KEY (CodServicio, NroActividad) REFERENCES ACTIVIDADES(CodServicio, NroActividad) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (NroOrenServ) REFERENCES ORDENES_SERVICIOS(Nro) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (CodProductoServ) REFERENCES PRODUCTOS_SERVICIOS(CodProd) ON UPDATE NO ACTION ON DELETE NO ACTION
);

